// Code generated by MockGen. DO NOT EDIT.
// Source: aws/infra_loader.go

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	gomock "github.com/golang/mock/gomock"
	aws "github.com/thomas.obenaus/inframapper/aws"
	reflect "reflect"
)

// MockInfraLoader is a mock of InfraLoader interface
type MockInfraLoader struct {
	ctrl     *gomock.Controller
	recorder *MockInfraLoaderMockRecorder
}

// MockInfraLoaderMockRecorder is the mock recorder for MockInfraLoader
type MockInfraLoaderMockRecorder struct {
	mock *MockInfraLoader
}

// NewMockInfraLoader creates a new mock instance
func NewMockInfraLoader(ctrl *gomock.Controller) *MockInfraLoader {
	mock := &MockInfraLoader{ctrl: ctrl}
	mock.recorder = &MockInfraLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInfraLoader) EXPECT() *MockInfraLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method
func (m *MockInfraLoader) Load() error {
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load
func (mr *MockInfraLoaderMockRecorder) Load() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockInfraLoader)(nil).Load))
}

// GetLoadedInfra mocks base method
func (m *MockInfraLoader) GetLoadedInfra() aws.Infra {
	ret := m.ctrl.Call(m, "GetLoadedInfra")
	ret0, _ := ret[0].(aws.Infra)
	return ret0
}

// GetLoadedInfra indicates an expected call of GetLoadedInfra
func (mr *MockInfraLoaderMockRecorder) GetLoadedInfra() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadedInfra", reflect.TypeOf((*MockInfraLoader)(nil).GetLoadedInfra))
}
