// Code generated by MockGen. DO NOT EDIT.
// Source: mappedInfra/infra.go

// Package mock_mappedInfra is a generated GoMock package.
package mock_mappedInfra

import (
	gomock "github.com/golang/mock/gomock"
	mappedInfra "github.com/thomasobenaus/inframapper/mappedInfra"
	reflect "reflect"
)

// MockInfra is a mock of Infra interface
type MockInfra struct {
	ctrl     *gomock.Controller
	recorder *MockInfraMockRecorder
}

// MockInfraMockRecorder is the mock recorder for MockInfra
type MockInfraMockRecorder struct {
	mock *MockInfra
}

// NewMockInfra creates a new mock instance
func NewMockInfra(ctrl *gomock.Controller) *MockInfra {
	mock := &MockInfra{ctrl: ctrl}
	mock.recorder = &MockInfraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInfra) EXPECT() *MockInfraMockRecorder {
	return m.recorder
}

// NumResources mocks base method
func (m *MockInfra) NumResources() int {
	ret := m.ctrl.Call(m, "NumResources")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumResources indicates an expected call of NumResources
func (mr *MockInfraMockRecorder) NumResources() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumResources", reflect.TypeOf((*MockInfra)(nil).NumResources))
}

// Resources mocks base method
func (m *MockInfra) Resources() []mappedInfra.MappedResource {
	ret := m.ctrl.Call(m, "Resources")
	ret0, _ := ret[0].([]mappedInfra.MappedResource)
	return ret0
}

// Resources indicates an expected call of Resources
func (mr *MockInfraMockRecorder) Resources() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resources", reflect.TypeOf((*MockInfra)(nil).Resources))
}

// AwsResourceByID mocks base method
func (m *MockInfra) AwsResourceByID(id string) mappedInfra.MappedResource {
	ret := m.ctrl.Call(m, "AwsResourceByID", id)
	ret0, _ := ret[0].(mappedInfra.MappedResource)
	return ret0
}

// AwsResourceByID indicates an expected call of AwsResourceByID
func (mr *MockInfraMockRecorder) AwsResourceByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwsResourceByID", reflect.TypeOf((*MockInfra)(nil).AwsResourceByID), id)
}

// MappedResources mocks base method
func (m *MockInfra) MappedResources() []mappedInfra.MappedResource {
	ret := m.ctrl.Call(m, "MappedResources")
	ret0, _ := ret[0].([]mappedInfra.MappedResource)
	return ret0
}

// MappedResources indicates an expected call of MappedResources
func (mr *MockInfraMockRecorder) MappedResources() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MappedResources", reflect.TypeOf((*MockInfra)(nil).MappedResources))
}

// UnMappedAwsResources mocks base method
func (m *MockInfra) UnMappedAwsResources() []mappedInfra.MappedResource {
	ret := m.ctrl.Call(m, "UnMappedAwsResources")
	ret0, _ := ret[0].([]mappedInfra.MappedResource)
	return ret0
}

// UnMappedAwsResources indicates an expected call of UnMappedAwsResources
func (mr *MockInfraMockRecorder) UnMappedAwsResources() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnMappedAwsResources", reflect.TypeOf((*MockInfra)(nil).UnMappedAwsResources))
}

// String mocks base method
func (m *MockInfra) String() string {
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String
func (mr *MockInfraMockRecorder) String() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockInfra)(nil).String))
}
