// Code generated by MockGen. DO NOT EDIT.
// Source: mappedInfra/mapper.go

// Package mock_mappedInfra is a generated GoMock package.
package mock_mappedInfra

import (
	gomock "github.com/golang/mock/gomock"
)
